source 'https://rubygems.org'

gem 'dashing'

## Remove this if you don't need a twitter widget.
gem 'twitter', '>= 5.9.0'
gem 'jira-ruby', :require => 'jira'
gem 'json'
gem 'google-api-client', '>= 0.8'
gem 'sinatra_cyclist'
